# 自定义属性
application:
  start: DEV
jwt:
  apiKey: keykeykey
  exp: 1800
  header: Authorization
mybatis:
  # mybatis mapper 位置
  mapper-locations: classpath:mapper/**/*Mapper.xml
server:
  # 服务器端口
  port: 8080
  session:
  # session 超时
    timeout: 1800
spring:
  datasource:
    # jdbc 驱动
    driver-class-name: com.mysql.jdbc.Driver
    # 数据库密码
    username: root
    # 数据库 url
    url: jdbc:mysql://localhost:3306/jurua-dev?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&autoReconnect=true
    # 密码
    password: root
  redis:
    # 数据库
    database: 0
    redisson:
      config: classpath:redisson.yaml
    # 主机
    host: localhost
    # 密码
    password: '# Login password of the redis server.'
    pool:
      # 最大连接数
      max-active: 8
      # 最小空闲连接数
      min-idle: 0
      # 最大空闲连接数
      max-idle: 8
      # 最大连接分配等待时间，负数为无限期等待
      max-wait: -1
    # redis 端口
    port: 6379