# 自定义属性
application:
  start: DEV
  # 采用 redisson 进行通知集群中一级缓存的清空工作，或者使用 rabbitmqNotice，将采用 rabbitmq 进行通知集群中一级缓存的清空工作
  broadcast: redissonNotice
jwt:
  apiKey: keykeykey
  exp: 1800
  header: Authorization
mybatis:
  # mybatis mapper 位置
  mapper-locations: classpath:mapper/**/*Mapper.xml
server:
  # 服务器端口
  port: 8081
  session:
  # session 超时
    timeout: 1800
spring:
  datasource:
    # 数据库 url
    druid:
      url: jdbc:mysql://localhost:3306/jurua_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&autoReconnect=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: s5#$Apex40DD
    # jdbc 驱动
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.mysql.jdbc.Driver
    # 数据库密码
#    username: root
    # 密码
#    password: s5#$Apex40DD

management:
  health:
    redis:
      enabled: false
    rabbit:
      enabled: false
rabbitmq:
  host: 127.0.0.1
  port: 5672
  userName: guest
  password: guest
  exchangeName: JURUA_API_RMQ_FANOUT
  exchangeType: fanout


